llm:
  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"  
  groq:
    provider: "groq"
    model_name: "llama3-8b-8192" 

  huggingface:
    provider: "huggingface"
    model_name: "microsoft/DialoGPT-medium"
